### PR TITLE
When debugging Logger does not register custom loggers.

### LINKED ISSUE #984: When debugging, logs are displayed twice
### Describe the problem you discovered

# Howto reproduce
1. launch aeWallet in debug mode
2. perform any operation
3. logs using `Logging` framework shows twice in debug console

### Describe the solution you'd like

_No response_

### Epic

_No response_

### PR DESCRIPTION
**Pull request by Chralu**
Fixes #984

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Material used:

- iOS (Mac)

## Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by redDwarf03** [comment]
Why in desktop mode, we have phoenix logs and not in web mode ?

**Comment by redDwarf03** [comment]
Tests ok in web mode, mobile mode and desktop mode

**Review by redDwarf03 — APPROVED** [review]

**Comment by Chralu** [comment]
> Why in desktop mode, we have phoenix logs and not in web mode ?

Ouch... Phoenix logs should appear.

Phoenix uses the same `Logging` framework as aeWallet, I would expect our setup to apply to Phoenix lib too.

I'll look into that issue.

**Comment by Chralu** [comment]
@redDwarf03 logs behave as expected to me. 

There are issues in websocket listening management. I created [an issue](https://github.com/archethic-foundation/archethic-wallet/issues/990) about that.

**Review by redDwarf03 — APPROVED** [review]

**Pull request merged**
