### PR TITLE
Image's size by screen density #491

### LINKED ISSUE #491: Image's size by screen density
### Describe the problem you discovered

for the images, it would be maybe interesting to decline them by screen density

### Describe the solution you'd like

Use https://docs.flutter.dev/development/ui/assets-and-images#resolution-aware

### PR DESCRIPTION
**Pull request by gdaguin**
I divided the initial images (png, jpg) into sub-images which depend on the resolution of the device

Fixes # (issue 741)

Type of change
Performance improvement
Material used:
Please delete options that are not relevant.

iOS (Smartphone/Tablet)
How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I tested my updates into simulator (iPhone 14 Pro Max, iPhone SE) and my personal iPhone SE
Patrol
Please list here the tests created in Patrol for this pull request.

Checklist:
My code follows the style guidelines of this project => yes
I have performed a self-review of my own code => yes
I have commented my code, particularly in hard-to-understand areas => no need to comment the code, juste images update
I have made corresponding changes to the documentation => yes
My changes generate no new warnings => yes
I have added tests that prove my fix is effective or that my feature works => yes
New and existing unit tests pass locally with my changes => yes
Any dependent changes have been merged and published in downstream modules => yes
Useful info for the reviewer:

### CODE REVIEW

**Comment by gdaguin** [comment]
Hello @redDwarf03 , why did you close this PR ? Did I make something wrong ?

**Comment by redDwarf03** [comment]
No that’s a Friday’s mistake 😅. Sorry

**Comment by redDwarf03** [comment]
For info, the PR titles are reused in changelog so it could be good to add a title more understanding please

**Comment by gdaguin** [comment]
> For info, the PR titles are reused in changelog so it could be good to add a title more understanding please

Ok good luck, that's a big one (not tricky at all bug sooooo long to review)

**Review by redDwarf03 — COMMENTED** [review]
We have a regression on 2 screens:

1) NFT Categories : https://github.com/archethic-foundation/archethic-wallet/blob/efce3fe8aaf7f9ba0596d2a4498b73a4712dc88f/lib/ui/views/nft/layouts/nft_category_menu.dart#L83

Before the PR: 

NFT without PR

Images in /archethic_wallet/assets/images

After the PR:

NFT with PR

2) NFT Category Home

https://github.com/archethic-foundation/archethic-wallet/blob/efce3fe8aaf7f9ba0596d2a4498b73a4712dc88f/lib/ui/views/nft/layouts/components/nft_list.dart#L57

Image in /archethic_wallet/assets/images/nft-empty.png

Before the PR:

NFT home without PR

After the PR:
 
NFT home with PR

**Comment by gdaguin** [comment]
Hello,

Sorry for the regressions, I fixed the issue.

**Comment by redDwarf03** [comment]
thank you (again) for you work!

**Pull request merged**
