### PR TITLE
UI Adjustements

### LINKED ISSUE #997: UI Adjustments
### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

- [x] : Add genesis address in main screen
- [x] : Calculate total USD Value in main screen
- [ ] : Calculate total USD Value for each service in Account Tab
- [x] : Move UCO info from main screen to tokens list tab
- [x] : Rework tokens list tab UI
- [x] : Add a new page for token detail

### PR DESCRIPTION
**Pull request by redDwarf03**
# Description

Fixes #997

## Type of change

- UI/UX design
- Refactorization

## Material used:

Please delete options that are not relevant.
- iOS (Mac)

## Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by IldySilva — APPROVED** [review]

**Comment by IldySilva** [comment]
@redDwarf03  what do wee need more to merge this ?
it's a must.

**Comment by redDwarf03** [comment]
> @redDwarf03 what do wee need more to merge this ? it's a must.

Bug fixing
The PR is a draft not ready to review

**Comment by IldySilva** [comment]
Can I provide any kind of support? I would like to work on Ui,Ux and Fix
some bugs
Al

**Comment by IldySilva** [comment]
> > @redDwarf03 what do wee need more to merge this ? it's a must.
> 
> Bug fixing The PR is a draft not ready to review
 @redDwarf03 
Can I offer  any kind of support? I would like to work on Ui,Ux and Fix some bugs

**Comment by redDwarf03** [comment]
> > > @redDwarf03 what do wee need more to merge this ? it's a must.
> > 
> > 
> > Bug fixing The PR is a draft not ready to review
> > @redDwarf03
> > Can I offer  any kind of support? I would like to work on Ui,Ux and Fix some bugs

Thanks but this PR is managed internally by Archethic 
You can help with other issues in backlog or ideally with wagmi new sdk in our repo

**Comment by redDwarf03** [comment]
@IldySilva 
I advice you to contribute here : 
- https://github.com/archethic-foundation/wagmi_flutter_web
- https://github.com/archethic-foundation/archethic-wallet/issues/1014
Some issue could be managed but this PR changes a lot of things

**Review by IldySilva — APPROVED** [review]

**Comment by redDwarf03** [comment]
I merge this too long PR to dev branch.
TODO after this in v3.0
- Import not certified tokens
- Disable fungibles tokens creation
- Fix null exception in SignTransactionsConfirmationForm
- Add DEX features
- Fix issues with local node (processes too fast)

**Pull request merged**
