### PR TITLE
[LockScreen] fixes and improvements

### LINKED ISSUE #653: Authent does not display background mask
### Describe the problem you discovered

# Description

## Steps to reproduce

1. on Android, setup Wallet to immediately lock using biometrics
2. quit Wallet using system "back" button
3. start Wallet again

## Expected behavior

Application is hidden by a background mask.
Application requires user biometric authentication.

## actual behavior

Application asks user biometric authentication. But application content is not hidden.

# Analyse

Background mask is displayed when application goes background.
But in this particular case, application is restarted from scratch.

We should add a check on startup too, to show background if necessary.

### Describe the solution you'd like

_No response_

### PR DESCRIPTION
**Pull request by Chralu**
🐛 On fresh start, authent displays background mask
🐛 hard killing app does not disable lock screen.
✨ LockScreen is displayed on timer end. And not on only on application focus.
🧱Migrate to GoRouter

Fixes #653

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Refactorization

## Material used:

Please delete options that are not relevant.
- iOS (Smartphone/Tablet)
- Android (Smartphone/Tablet)
- Browser
- Linux
- Windows
- iOS (Mac)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

### Patrol

Please list here the tests created in Patrol for this pull request.

## Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by redDwarf03 — COMMENTED** [review]
Why do you publish news `project.pbxproj` files ?

**Review by redDwarf03 — CHANGES_REQUESTED** [review]
If authent at launch option is = no, the authent is still necessary

**Comment by redDwarf03** [comment]
@Chralu i need your help to 
[ ] - start scheduleAutolock without new timer 
[ ] - welcome process, the timer shouldn't work
[ ] - if user change his settings, the timer should be updated

**Comment by redDwarf03** [comment]
- Bug: Not working when we use keyboard. The app locks after X seconds even if we use keyboard
- Bug: Strange but when we go to NFT detail, the app locks after X seconds without take in account the last click
- UX: Desktop: When we click on an external link, the saver screen appears but i think it's not necessary
- UX: Perhaps it will be better to display when the app locks the screen saver instead of the authent screen (in Face ID or Touch ID, we have the screen saver but not with PIN

**Comment by Chralu** [comment]
@redDwarf03 PR set to Draft : [GoRouter integration](#862) is required to finalize this PR.

**Review by redDwarf03 — APPROVED** [review]

**Pull request merged**
