### PR TITLE
Improve auto lock settings

### LINKED ISSUE #941: Improve auto lock settings
# Is your feature request related to a problem?

Lock settings mix multiple things in only one parameter :
 - Hiding screen when app is in background
 - Auto-locking app after a delay (ask for user authentication to unlock app)
 
This might be confusing for users who want to disable only one of those features.

# Describe the solution you'd like

## Setting `Hide screen when application in background`
mask_screen

### Behavior : 
Mask screen is an overlay which hides **AEWallet** content when **AEWallet** is in background.
It is useful to hide sensitive data while switching to another app.
Mask should be enabled on **mobile** platforms only. 

### default value : 
  - desktop : `disabled`
  - web : `disabled`
  - mobile : `enabled`

> ## Setting `Lock on startup`   : Abandoned => see comments
> 
> ### Behavior : 
> When enabled, requires user authentication when application is started from zero.
> This handles the case of the wallet not being locked on close / quit / force quit.
> 
> ### values :  `[enabled | disabled]`
> ### default value : 
>   - desktop : `enabled`
>   - web : `disabled`
>   - mobile : `disabled`

### Behavior : 
Delay to lock application when there is no user interaction.

### default value : `1min`

### PR DESCRIPTION
**Pull request by Chralu**
Fixes #941

### CODE REVIEW

**Comment by redDwarf03** [comment]
Desktop (with macOS). 
- [x] Mask screen on background : Tests ok  
- [x] Auto lock durations : Test ok

Mobile (with ios). 
- [x] Mask screen on background : Tests ok  
- [x] Auto lock durations : See comment below

Web (with chrome). 
- [x] Auto lock durations :  See comment below

**Comment by redDwarf03** [comment]
when i launch in mobile mode the app, after fill the pin, the duration of the displaying of message about jailbreak is too short

**Review by redDwarf03 — COMMENTED** [review]
when i launch in mobile mode the app, after fill the pin, the duration of the displaying of message about jailbreak is too short

**Comment by redDwarf03** [comment]
i launched the wallet which had an activated account. i got the pin code to access the account and the console noted that under macos

```2024-06-12 09:22:17.699 archethic_wallet[7683:57586] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.```

**Comment by redDwarf03** [comment]
With FaceID and ios simulator (not true device), when the autolock is activated, if the option "Mask screen in background" is disabled, the autolock displays the overlay but is not, the overlay is not displayed.
So someone can see the wallet info before the authent.
I can't test now with true device

**Comment by redDwarf03** [comment]
Hiding screen when app is in background doesn't work in web mode

**Comment by redDwarf03** [comment]
in web mode, we can click many times on validate button on authent screen because the delay to authenticate the user is a little long

Capture d’écran 2024-06-12 à 09 43 13

And click many times generate this error 
```
Error
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
packages/flutter/src/widgets/framework.dart 951:9                            <fn>
packages/flutter/src/widgets/framework.dart 956:14                           get context
packages/aewallet/ui/views/authenticate/password_screen.dart 86:9            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
Error
```


Disable the validate button while this delay to prevent this error.

**Comment by Chralu** [comment]
> in web mode, we can click many times on validate button on authent screen because the delay to authenticate the user is a little long
> Capture d’écran 2024-06-12 à 09 43 13
> 
> And click many times generate this error
> 
> ```
> Error
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
> packages/flutter/src/widgets/framework.dart 951:9                            <fn>
> packages/flutter/src/widgets/framework.dart 956:14                           get context
> packages/aewallet/ui/views/authenticate/password_screen.dart 86:9            <fn>
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
> dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
> dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
> dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
> dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
> dart-sdk/lib/async/future_impl.dart 713:7                                    callback
> dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
> dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
> Error
> ```
> 
> Disable the validate button while this delay to prevent this error.

Duplicate #975

**Comment by Chralu** [comment]
@redDwarf03 everything should be fine now.

Notice there is [still a bug](https://github.com/archethic-foundation/archethic-wallet/issues/982) when creating a wallet with biometric authent. This will be fixed in another PR.

**Review by redDwarf03 — APPROVED** [review]

**Pull request merged**
